name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create project directory if it doesn't exist
            PROJECT_DIR="/home/${{ secrets.REMOTE_USER }}/fastapi-book-project"
            mkdir -p $PROJECT_DIR

            # Update or clone repository
            if [ -d "$PROJECT_DIR/.git" ]; then
              cd $PROJECT_DIR
              git pull
            else
              git clone https://github.com/Skibo555/fastapi-book-project.git $PROJECT_DIR
              cd $PROJECT_DIR
            fi

            # Install Docker if not present
            if ! command -v docker &> /dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt-get update -y
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            fi

            # Install Docker Compose if not present
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Deploy
            docker-compose down || true  # Don't fail if containers aren't running
            docker-compose up -d --build
